---

- name: Install docker
  become: true
  apt:
    name: docker.io
    state: latest

- name: Docker group exists
  become: true
  group:
    name: docker
    state: present

- name: Working user belongs to docker group
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    state: present
    groups: docker
    append: yes

- name: Docker daemon status is started
  systemd:
    name: docker
    state: started

- name: Set variable OS target
  shell: echo $((uanme -s))-$((uname -m))
  register: os
  changed_when: no

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ os }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
